set gaSet(sw)          "0"
set gaSet(dbrSW)       "6.8.4(0.65)"
set gaSet(swPack)      "SW3260"
set gaSet(dbrBVerSw)   "SW3307"
set gaSet(dbrBVer)     "2.0.0(0.07)"
set gaSet(cpld)        "11"
set gaSet(DutFullName) "ETX-2I/AC/M"
set gaSet(DutInitName) "ETX-2I.AC.M.tcl"
set gaSet(BootCF) "C:/download/Boot/vxboot.bin"
set gaSet(SWCF) "C:/Users/ate-j-r/Desktop/6.8.4(0.65)/sw-pack_2i.bin"
set gaSet(19VCF) "C:/AT-ETX-2i/ConfFiles/data19v.txt"
set gaSet(19CF) "C:/AT-ETX-2i/ConfFiles/data19.txt"
set gaSet(MCF) "C:/AT-ETX-2i/ConfFiles/dataM.txt"
set gaSet(DGaspCF) "C:/AT-ETX-2i/software/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2i/ConfFiles/RtRtest.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(DefaultCF) ""
set gaSet(Half19CF) "C:/AT-ETX-2i/ConfFiles/data19.txt"
set gaSet(Half19_loopCF) "C:/AT-ETX-2i/software/ConfFiles/data_dt_1.txt"
set gaSet(Half19_4portsCF) "C:/AT-ETX-2i/software/ConfFiles/data_dt_2.txt"
set gaSet(dnfvProject) "Z740- 008"
set gaSet(dnfvEC) "00 10"
set gaSet(dnfvCPU) "i74700EQ CPU @ 2.40Ghz"
set gaSet(licDir) ""
set gaSet(dnfvVer) "??"
