set gaSet(sw)          "0"
set gaSet(dbrSW)       "1.1.0(0.016)"
set gaSet(swPack)      "SW3261"
set gaSet(dbrBVerSw)   "??"
set gaSet(dbrBVer)     "??"
set gaSet(cpld)        "??"
set gaSet(DutFullName) "ETX-DNFV-M/I7/128S/8R"
set gaSet(DutInitName) "ETX-DNFV-M.I7.128S.8R.tcl"
set gaSet(19VCF) "c:/aa"
set gaSet(19CF) "C:/AT-ETX-2i/ConfFiles/data19.txt"
set gaSet(MCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2i/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) "C:/AT-ETX-2i/ConfFiles/EXTCLOCK.txt"
set gaSet(RTRCF) "C:/AT-ETX-2i/ConfFiles/RtRtest.txt"
set gaSet(DNFVCF) "C:/AT-ETX-2i/ConfFiles/dnfv14.txt"
set gaSet(dnfvProject) "Z740- 0.08"
set gaSet(dnfvEC) "00 10"
set gaSet(dnfvCPU) "i7-4700EQ CPU @ 2.40GHz"
set gaSet(licDir) "???"
set gaSet(dnfvVer) "1.1.0.011"
