set gaSet(sw)          "5.9.1(0.35)"
set gaSet(dbrSW)       "6.2.1(0.39)"
set gaSet(swPack)      "SW3260"
set gaSet(DutFullName) "ETX-2I/AC/M/PTP"
set gaSet(DutInitName) "ETX-2I.AC.M.PTP.tcl"
set gaSet(19VCF) "C:/AT-ETX-2i/ConfFiles/data19v.txt"
set gaSet(19CF) "C:/AT-ETX-2i/ConfFiles/data19.txt"
set gaSet(MCF) "C:/AT-ETX-2i/ConfFiles/dataM.txt"
set gaSet(DGaspCF) "C:/AT-ETX-2i/ConfFiles/Dying Gasp_via_eth01.txt"
set gaSet(ExtClkCF) "C:/AT-ETX-2i/ConfFiles/EXTCLOCK.txt"
set gaSet(RTRCF) "C:/AT-ETX-2i/ConfFiles/RtRtest.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) ""
set gaSet(dnfvVer) "??"
