set gaGui(xy) +274+12
set gaSet(entDUT) "ETX-2I/AC/19/RTR"
set gaSet(DutInitName) "ETX-2I.AC.19.RTR.tcl"
set gaSet(performShortTest) "0"
set gaSet(eraseTitle) "0"
set gaSet(ddrMultyQty) "5"
set gaSet(DGTestQty) "3"
set gaSet(DGTestLoopBreak) "1"
set gaSet(performDownloadSteps) "1"
