set gaGui(xy) +257+473
set gaSet(entDUT) "ETX-2I_FT/ACHP/19V"
set gaSet(DutInitName) "ETX-2I_FT.ACHP.19V.tcl"
set gaSet(performShortTest) "0"
set gaSet(eraseTitle) "0"
set gaSet(ddrMultyQty) "5"
set gaSet(DGTestQty) "3"
set gaSet(DGTestLoopBreak) "1"
set gaSet(performDownloadSteps) "1"
