set gaGui(xy) +168+315
set gaSet(entDUT) "ETX-2I/H/AC/19/PTP/RTR"
set gaSet(DutInitName) "ETX-2I.H.AC.19.PTP.RTR.tcl"
set gaSet(performShortTest) "0"
set gaSet(eraseTitle) "0"
set gaSet(ddrMultyQty) "5"
set gaSet(DGTestQty) "3"
set gaSet(DGTestLoopBreak) "1"
set gaSet(performDownloadSteps) "1"
