set gaGui(xy) +408+159
set gaSet(entDUT) "ETX-2I_FT/AC/19M/PTP"
set gaSet(DutInitName) "ETX-2I_FT.AC.19M.PTP.tcl"
set gaSet(performShortTest) "0"
set gaSet(eraseTitle) "0"
set gaSet(ddrMultyQty) "5"
set gaSet(DGTestQty) "3"
set gaSet(DGTestLoopBreak) "1"
set gaSet(performDownloadSteps) "1"
